site_name: todo
site_description: Todo backend
repo_url: https://github.com/wdrescher/founder-base-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/wdrescher">wdrescher</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
