# Generated by Django 3.1.2 on 2020-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
